config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'cat_toys/new'
  get 'cat_toys/create'
  get 'cat_toys/show'
  get 'cat_toys/index'
  resources :cats
  resources :cat_memes
  resources :users

  get '/all_the_cat_memes', to: "cat_memes#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/cat_meme.rb
class CatMeme < ApplicationRecord
  belongs_to :user
end

app/models/cat_toy.rb
class CatToy < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # custom helper methods go here...
end

app/controllers/cat_memes_controller.rb
class CatMemesController < ApplicationController
  before_action :set_cat_meme, only: [:show, :edit, :update, :destroy]

  # GET /cat_memes
  # GET /cat_memes.json
  def index
    @cat_memes = CatMeme.all
  end

  # # Sinatra - Route is defined in the controller and the action supplied with a block
  # get '/cat_memes' do
  #
  # end

  # GET /cat_memes/1
  # GET /cat_memes/1.json
  def show
  end

  # GET /cat_memes/new
  def new
    @cat_meme = CatMeme.new
  end

  # GET /cat_memes/1/edit
  def edit
  end

  # POST /cat_memes
  # POST /cat_memes.json
  def create
    @cat_meme = CatMeme.new(cat_meme_params)

    respond_to do |format|
      if @cat_meme.save
        format.html { redirect_to @cat_meme, notice: 'Cat meme was successfully created.' }
        format.json { render :show, status: :created, location: @cat_meme }
      else
        format.html { render :new }
        format.json { render json: @cat_meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_memes/1
  # PATCH/PUT /cat_memes/1.json
  def update
    respond_to do |format|
      if @cat_meme.update(cat_meme_params)
        format.html { redirect_to @cat_meme, notice: 'Cat meme was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat_meme }
      else
        format.html { render :edit }
        format.json { render json: @cat_meme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_memes/1
  # DELETE /cat_memes/1.json
  def destroy
    @cat_meme.destroy
    respond_to do |format|
      format.html { redirect_to cat_memes_url, notice: 'Cat meme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_meme
      @cat_meme = CatMeme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_meme_params
      params.require(:cat_meme).permit(:title, :alt, :user_id, :image_url)
    end
end

app/controllers/cat_toys_controller.rb
class CatToysController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def index
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  end

  def destroy

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_memes_helper.rb
module CatMemesHelper
end

app/helpers/cat_toys_helper.rb
module CatToysHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_memes/_form.html.erb
<%= form_with(model: cat_meme, local: true) do |form| %>
  <% if cat_meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat_meme.errors.count, "error") %> prohibited this cat_meme from being saved:</h2>

      <ul>
        <% cat_meme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :alt %>
    <%= form.text_field :alt %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cat_memes/edit.html.erb
<h1>Editing Cat Meme</h1>

<%= render 'form', cat_meme: @cat_meme %>

<%= link_to 'Show', @cat_meme %> |
<%= link_to 'Back', cat_memes_path %>

app/views/cat_memes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cat Memes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Alt</th>
      <th>User</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cat_memes.each do |cat_meme| %>
      <tr>
        <td><%= cat_meme.title %></td>
        <td><%= cat_meme.alt %></td>
        <td><%= cat_meme.user_id %></td>
        <td><%= cat_meme.image_url %></td>
        <td><%= link_to 'Show', cat_meme %></td>
        <td><%= link_to 'Edit', edit_cat_meme_path(cat_meme) %></td>
        <td><%= link_to 'Destroy', cat_meme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat Meme', new_cat_meme_path %>

app/views/cat_memes/new.html.erb
<h1>New Cat Meme</h1>

<%= render 'form', cat_meme: @cat_meme %>

<%= link_to 'Back', cat_memes_path %>

app/views/cat_memes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cat_meme.title %>
</p>

<p>
  <strong>Alt:</strong>
  <%= @cat_meme.alt %>
</p>

<p>
  <strong>User:</strong>
  <%= @cat_meme.user_id %>
</p>

  <img src="<%= @cat_meme.image_url %>" alt="<%= @cat_meme.alt %>">

<%= link_to 'Edit', edit_cat_meme_path(@cat_meme) %> |
<%= link_to 'Back', cat_memes_path %>

app/views/cat_toys/index.html.erb
<h1>CatToys#index</h1>
<p>Find me in app/views/cat_toys/index.html.erb</p>

app/views/cat_toys/new.html.erb
<h1>CatToys#new</h1>
<p>Find me in app/views/cat_toys/new.html.erb</p>

app/views/cat_toys/show.html.erb
<h1>CatToys#show</h1>
<p>Find me in app/views/cat_toys/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatMemes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>